name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install Poetry
        uses: python-poetry/poetry@v1
        with:
          version: '1.8.2'
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
      - name: Run pytest
        run: poetry run pytest
